/run/numberOfThreads 6

/control/verbose 2
/run/verbose 2

/Geometry/HPGeDetector/enable
/Geometry/HPGeDetector/rotateY 0 deg

/Geometry/HPGeDetector/position 0 0 0 mm

/Geometry/TargetHolderC12/enable
/Geometry/TargetHolderC12/target evaporated
/Geometry/TargetHolderC12/position 0 0 -20 mm

/run/initialize

/PrimaryGenerator/select GammaDecayScheme
/PrimaryGenerator/GammaDecayScheme/position 0.6830713094007415 0.08087592023447154 -2.1 cm
/PrimaryGenerator/GammaDecayScheme/levelFile data/14N.txt
/PrimaryGenerator/GammaDecayScheme/excitedState 7824 keV

#/run/setFileName 13C_pg_0.6830713094007415_0.08087592023447154.root

/run/beamOn 1000000
